name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
      version:
        description: 'Version of deployment'
        required: true
        default: '1.1.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying to ${{ github.event.inputs.environment }} with version ${{ github.event.inputs.version }}"
